/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef F29BMS_DBC_H
#define F29BMS_DBC_H

#include <stdint.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

typedef PREPACK struct {
	uint8_t BmsStatus_SOC; /* scaling 1.0, offset 0.0, units %  */
	uint8_t BmsStatus_SOC_raw; /* scaling 1.0, offset 0.0, units %  */
	uint8_t BmsStatus_ChargeState; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x258_BmsStatus_t;

typedef PREPACK struct {
	uint8_t BmsFaultVector_SLAVE_COMM_CELLS; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultVector_SLAVE_COMM_TEMPS; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultVector_SLAVE_COMM_DRAIN_REQUEST; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultVector_CURRENT_SENSOR_COMM; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultVector_OVER_CURRENT; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultVector_CELL_VOLTAGE_IRRATIONAL; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultVector_CELL_VOLTAGE_DIFF; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultVector_OUT_OF_JUICE; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultVector_TEMPERATURE_IRRATIONAL; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultVector_OVER_TEMPERATURE; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultVector_DRAIN_FAILURE; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x2bc_BmsFaultVector_t;

typedef PREPACK struct {
	uint32_t BmsFaultAlert_current; /* scaling 0.0, offset 0.0, units A  */
	uint16_t BmsFaultAlert_irrational_temperature; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsFaultAlert_over_temperature; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsFaultAlert_irrational_voltage; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsFaultAlert_voltage_diff; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsFaultAlert_lowest_cell_voltage; /* scaling 0.0, offset 0.0, units V  */
	uint8_t BmsFaultAlert_cell_comm_slave_board_num; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultAlert_temp_comm_slave_board_num; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultAlert_drain_comm_slave_board_num; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultAlert_adc_error_code; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultAlert_failed_drain_cell; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BmsFaultAlert_code; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x2bd_BmsFaultAlert_t;

typedef PREPACK struct {
	uint16_t BmsVoltages_Cell0; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell6; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell12; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell18; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell24; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell30; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell36; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell42; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell48; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell54; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell60; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell66; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell72; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell78; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell84; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell1; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell7; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell13; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell19; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell25; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell31; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell37; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell43; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell49; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell55; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell61; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell67; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell73; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell79; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell85; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell2; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell8; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell14; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell20; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell26; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell32; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell38; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell44; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell50; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell56; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell62; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell68; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell74; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell80; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell86; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell3; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell9; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell15; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell21; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell27; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell33; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell39; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell45; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell51; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell57; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell63; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell69; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell75; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell81; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell87; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell4; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell10; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell16; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell22; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell28; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell34; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell40; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell46; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell52; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell58; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell64; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell70; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell76; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell82; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell88; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell5; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell11; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell17; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell23; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell29; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell35; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell41; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell47; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell53; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell59; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell65; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell71; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell77; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell83; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsVoltages_Cell89; /* scaling 0.0, offset 0.0, units V  */
	uint8_t BmsVoltages_mux; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x2be_BmsVoltages_t;

typedef PREPACK struct {
	uint16_t BmsThermistorVoltages_tm0; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm6; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm12; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm18; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm1; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm7; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm13; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm19; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm2; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm8; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm14; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm3; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm9; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm15; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm4; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm10; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm16; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm5; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm11; /* scaling 0.0, offset 0.0, units V  */
	uint16_t BmsThermistorVoltages_tm17; /* scaling 0.0, offset 0.0, units V  */
	uint8_t BmsThermistorVoltages_mux; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x2bf_BmsThermistorVoltages_t;

typedef PREPACK struct {
	int8_t BmsTemperatures_0; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_7; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_14; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_1; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_8; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_15; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_2; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_9; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_16; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_3; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_10; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_17; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_4; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_11; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_18; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_5; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_12; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_19; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_6; /* scaling 1.0, offset 0.0, units C  */
	int8_t BmsTemperatures_13; /* scaling 1.0, offset 0.0, units C  */
	uint8_t BmsTemperatures_mux; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x2c0_BmsTemperatures_t;

typedef PREPACK struct {
	uint64_t BmsDrainStatus_Cells0to63; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x320_BmsDrainStatusA_t;

typedef PREPACK struct {
	uint32_t BmsDrainStatus_Cells64to89; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x321_BmsDrainStatusB_t;

typedef PREPACK struct {
	uint32_t BmsInstCurrentFilt; /* scaling 0.0, offset 0.0, units A  */
} POSTPACK can_0x384_BmsCurrent_t;

typedef PREPACK struct {
	uint16_t BmsChargeRequest_MaxVoltage; /* scaling 0.1, offset 0.0, units V  */
	uint16_t BmsChargeRequest_MaxCurrent; /* scaling 0.1, offset 0.0, units A  */
	uint8_t BmsChargeRequest_Control; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x9806e5f4_BmsChargeRequest_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x258_BmsStatus_time_stamp_rx;
	dbcc_time_stamp_t can_0x2bc_BmsFaultVector_time_stamp_rx;
	dbcc_time_stamp_t can_0x2bd_BmsFaultAlert_time_stamp_rx;
	dbcc_time_stamp_t can_0x2be_BmsVoltages_time_stamp_rx;
	dbcc_time_stamp_t can_0x2bf_BmsThermistorVoltages_time_stamp_rx;
	dbcc_time_stamp_t can_0x2c0_BmsTemperatures_time_stamp_rx;
	dbcc_time_stamp_t can_0x320_BmsDrainStatusA_time_stamp_rx;
	dbcc_time_stamp_t can_0x321_BmsDrainStatusB_time_stamp_rx;
	dbcc_time_stamp_t can_0x384_BmsCurrent_time_stamp_rx;
	dbcc_time_stamp_t can_0x9806e5f4_BmsChargeRequest_time_stamp_rx;
	unsigned can_0x258_BmsStatus_status : 2;
	unsigned can_0x258_BmsStatus_tx : 1;
	unsigned can_0x258_BmsStatus_rx : 1;
	unsigned can_0x2bc_BmsFaultVector_status : 2;
	unsigned can_0x2bc_BmsFaultVector_tx : 1;
	unsigned can_0x2bc_BmsFaultVector_rx : 1;
	unsigned can_0x2bd_BmsFaultAlert_status : 2;
	unsigned can_0x2bd_BmsFaultAlert_tx : 1;
	unsigned can_0x2bd_BmsFaultAlert_rx : 1;
	unsigned can_0x2be_BmsVoltages_status : 2;
	unsigned can_0x2be_BmsVoltages_tx : 1;
	unsigned can_0x2be_BmsVoltages_rx : 1;
	unsigned can_0x2bf_BmsThermistorVoltages_status : 2;
	unsigned can_0x2bf_BmsThermistorVoltages_tx : 1;
	unsigned can_0x2bf_BmsThermistorVoltages_rx : 1;
	unsigned can_0x2c0_BmsTemperatures_status : 2;
	unsigned can_0x2c0_BmsTemperatures_tx : 1;
	unsigned can_0x2c0_BmsTemperatures_rx : 1;
	unsigned can_0x320_BmsDrainStatusA_status : 2;
	unsigned can_0x320_BmsDrainStatusA_tx : 1;
	unsigned can_0x320_BmsDrainStatusA_rx : 1;
	unsigned can_0x321_BmsDrainStatusB_status : 2;
	unsigned can_0x321_BmsDrainStatusB_tx : 1;
	unsigned can_0x321_BmsDrainStatusB_rx : 1;
	unsigned can_0x384_BmsCurrent_status : 2;
	unsigned can_0x384_BmsCurrent_tx : 1;
	unsigned can_0x384_BmsCurrent_rx : 1;
	unsigned can_0x9806e5f4_BmsChargeRequest_status : 2;
	unsigned can_0x9806e5f4_BmsChargeRequest_tx : 1;
	unsigned can_0x9806e5f4_BmsChargeRequest_rx : 1;
	can_0x258_BmsStatus_t can_0x258_BmsStatus;
	can_0x2bc_BmsFaultVector_t can_0x2bc_BmsFaultVector;
	can_0x2bd_BmsFaultAlert_t can_0x2bd_BmsFaultAlert;
	can_0x2be_BmsVoltages_t can_0x2be_BmsVoltages;
	can_0x2bf_BmsThermistorVoltages_t can_0x2bf_BmsThermistorVoltages;
	can_0x2c0_BmsTemperatures_t can_0x2c0_BmsTemperatures;
	can_0x320_BmsDrainStatusA_t can_0x320_BmsDrainStatusA;
	can_0x321_BmsDrainStatusB_t can_0x321_BmsDrainStatusB;
	can_0x384_BmsCurrent_t can_0x384_BmsCurrent;
	can_0x9806e5f4_BmsChargeRequest_t can_0x9806e5f4_BmsChargeRequest;
} POSTPACK can_obj_f29bms_dbc_h_t;

int unpack_message(can_obj_f29bms_dbc_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message(can_obj_f29bms_dbc_h_t *o, const unsigned long id, uint64_t *data);
int print_message(const can_obj_f29bms_dbc_h_t *o, const unsigned long id, FILE *output);

int decode_can_0x258_BmsStatus_SOC(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x258_BmsStatus_SOC(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x258_BmsStatus_SOC_raw(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x258_BmsStatus_SOC_raw(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x258_BmsStatus_ChargeState(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x258_BmsStatus_ChargeState(can_obj_f29bms_dbc_h_t *o, uint8_t in);


int decode_can_0x2bc_BmsFaultVector_SLAVE_COMM_CELLS(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_SLAVE_COMM_CELLS(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bc_BmsFaultVector_SLAVE_COMM_TEMPS(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_SLAVE_COMM_TEMPS(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bc_BmsFaultVector_SLAVE_COMM_DRAIN_REQUEST(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_SLAVE_COMM_DRAIN_REQUEST(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bc_BmsFaultVector_CURRENT_SENSOR_COMM(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_CURRENT_SENSOR_COMM(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bc_BmsFaultVector_OVER_CURRENT(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_OVER_CURRENT(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bc_BmsFaultVector_CELL_VOLTAGE_IRRATIONAL(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_CELL_VOLTAGE_IRRATIONAL(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bc_BmsFaultVector_CELL_VOLTAGE_DIFF(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_CELL_VOLTAGE_DIFF(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bc_BmsFaultVector_OUT_OF_JUICE(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_OUT_OF_JUICE(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bc_BmsFaultVector_TEMPERATURE_IRRATIONAL(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_TEMPERATURE_IRRATIONAL(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bc_BmsFaultVector_OVER_TEMPERATURE(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_OVER_TEMPERATURE(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bc_BmsFaultVector_DRAIN_FAILURE(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bc_BmsFaultVector_DRAIN_FAILURE(can_obj_f29bms_dbc_h_t *o, uint8_t in);


int decode_can_0x2bd_BmsFaultAlert_current(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bd_BmsFaultAlert_current(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bd_BmsFaultAlert_irrational_temperature(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bd_BmsFaultAlert_irrational_temperature(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bd_BmsFaultAlert_over_temperature(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bd_BmsFaultAlert_over_temperature(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bd_BmsFaultAlert_irrational_voltage(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bd_BmsFaultAlert_irrational_voltage(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bd_BmsFaultAlert_voltage_diff(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bd_BmsFaultAlert_voltage_diff(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bd_BmsFaultAlert_lowest_cell_voltage(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bd_BmsFaultAlert_lowest_cell_voltage(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bd_BmsFaultAlert_cell_comm_slave_board_num(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bd_BmsFaultAlert_cell_comm_slave_board_num(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bd_BmsFaultAlert_temp_comm_slave_board_num(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bd_BmsFaultAlert_temp_comm_slave_board_num(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bd_BmsFaultAlert_drain_comm_slave_board_num(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bd_BmsFaultAlert_drain_comm_slave_board_num(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bd_BmsFaultAlert_adc_error_code(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bd_BmsFaultAlert_adc_error_code(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bd_BmsFaultAlert_failed_drain_cell(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bd_BmsFaultAlert_failed_drain_cell(can_obj_f29bms_dbc_h_t *o, uint8_t in);
int decode_can_0x2bd_BmsFaultAlert_code(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bd_BmsFaultAlert_code(can_obj_f29bms_dbc_h_t *o, uint8_t in);


int decode_can_0x2be_BmsVoltages_Cell0(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell0(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell6(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell6(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell12(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell12(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell18(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell18(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell24(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell24(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell30(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell30(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell36(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell36(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell42(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell42(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell48(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell48(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell54(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell54(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell60(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell60(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell66(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell66(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell72(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell72(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell78(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell78(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell84(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell84(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell1(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell1(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell7(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell7(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell13(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell13(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell19(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell19(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell25(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell25(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell31(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell31(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell37(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell37(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell43(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell43(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell49(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell49(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell55(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell55(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell61(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell61(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell67(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell67(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell73(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell73(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell79(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell79(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell85(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell85(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell2(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell2(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell8(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell8(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell14(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell14(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell20(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell20(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell26(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell26(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell32(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell32(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell38(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell38(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell44(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell44(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell50(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell50(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell56(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell56(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell62(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell62(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell68(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell68(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell74(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell74(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell80(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell80(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell86(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell86(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell3(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell3(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell9(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell9(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell15(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell15(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell21(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell21(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell27(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell27(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell33(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell33(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell39(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell39(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell45(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell45(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell51(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell51(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell57(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell57(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell63(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell63(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell69(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell69(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell75(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell75(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell81(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell81(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell87(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell87(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell4(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell4(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell10(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell10(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell16(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell16(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell22(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell22(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell28(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell28(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell34(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell34(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell40(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell40(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell46(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell46(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell52(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell52(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell58(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell58(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell64(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell64(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell70(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell70(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell76(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell76(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell82(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell82(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell88(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell88(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell5(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell5(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell11(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell11(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell17(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell17(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell23(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell23(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell29(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell29(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell35(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell35(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell41(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell41(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell47(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell47(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell53(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell53(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell59(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell59(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell65(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell65(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell71(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell71(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell77(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell77(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell83(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell83(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_Cell89(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2be_BmsVoltages_Cell89(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2be_BmsVoltages_mux(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2be_BmsVoltages_mux(can_obj_f29bms_dbc_h_t *o, uint8_t in);


int decode_can_0x2bf_BmsThermistorVoltages_tm0(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm0(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm6(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm6(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm12(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm12(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm18(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm18(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm1(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm1(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm7(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm7(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm13(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm13(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm19(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm19(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm2(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm2(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm8(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm8(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm14(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm14(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm3(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm3(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm9(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm9(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm15(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm15(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm4(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm4(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm10(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm10(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm16(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm16(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm5(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm5(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm11(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm11(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_tm17(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x2bf_BmsThermistorVoltages_tm17(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x2bf_BmsThermistorVoltages_mux(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2bf_BmsThermistorVoltages_mux(can_obj_f29bms_dbc_h_t *o, uint8_t in);


int decode_can_0x2c0_BmsTemperatures_0(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_0(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_7(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_7(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_14(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_14(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_1(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_1(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_8(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_8(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_15(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_15(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_2(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_2(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_9(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_9(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_16(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_16(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_3(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_3(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_10(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_10(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_17(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_17(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_4(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_4(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_11(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_11(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_18(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_18(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_5(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_5(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_12(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_12(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_19(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_19(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_6(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_6(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_13(const can_obj_f29bms_dbc_h_t *o, int8_t *out);
int encode_can_0x2c0_BmsTemperatures_13(can_obj_f29bms_dbc_h_t *o, int8_t in);
int decode_can_0x2c0_BmsTemperatures_mux(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x2c0_BmsTemperatures_mux(can_obj_f29bms_dbc_h_t *o, uint8_t in);


int decode_can_0x320_BmsDrainStatus_Cells0to63(const can_obj_f29bms_dbc_h_t *o, uint64_t *out);
int encode_can_0x320_BmsDrainStatus_Cells0to63(can_obj_f29bms_dbc_h_t *o, uint64_t in);


int decode_can_0x321_BmsDrainStatus_Cells64to89(const can_obj_f29bms_dbc_h_t *o, uint32_t *out);
int encode_can_0x321_BmsDrainStatus_Cells64to89(can_obj_f29bms_dbc_h_t *o, uint32_t in);


int decode_can_0x384_BmsInstCurrentFilt(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x384_BmsInstCurrentFilt(can_obj_f29bms_dbc_h_t *o, double in);


int decode_can_0x9806e5f4_BmsChargeRequest_MaxVoltage(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x9806e5f4_BmsChargeRequest_MaxVoltage(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x9806e5f4_BmsChargeRequest_MaxCurrent(const can_obj_f29bms_dbc_h_t *o, double *out);
int encode_can_0x9806e5f4_BmsChargeRequest_MaxCurrent(can_obj_f29bms_dbc_h_t *o, double in);
int decode_can_0x9806e5f4_BmsChargeRequest_Control(const can_obj_f29bms_dbc_h_t *o, uint8_t *out);
int encode_can_0x9806e5f4_BmsChargeRequest_Control(can_obj_f29bms_dbc_h_t *o, uint8_t in);


#ifdef __cplusplus
} 
#endif

#endif
