/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4-dev */

#include "BmsSim.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(BmsMetaData, BmsMetaData, AUTO)


PB_BIND(BmsData, BmsData, 2)


PB_BIND(BmsIn, BmsIn, AUTO)


PB_BIND(ThermList, ThermList, AUTO)


PB_BIND(Therm, Therm, AUTO)


PB_BIND(BmsOut, BmsOut, AUTO)


PB_BIND(CanMessage, CanMessage, AUTO)


PB_BIND(CellList, CellList, 2)


PB_BIND(Cell, Cell, AUTO)



